[package]
name = "shooter-game"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "shooter-game-run"
path = "src/main.rs"

# build a static rust lib (rlib) and c++ compatible libary (cdylib)
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytemuck = { version = "1.13.1", features = ["derive"] }
cfg-if = "1.0.0"
env_logger = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.20"
pollster = "0.3.0"
wasm-bindgen-futures = "0.4.37"
wgpu = "0.17.0"
winit = "0.28.6"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { version = "0.17", features = ["webgl"]}

# send panic errors to js console
console_error_panic_hook = "0.1.7"
console_log = "1.0"

# generate wasm compatible web boilerplate code
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
]}
