name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build editor
      run: cargo check --bin editor
    - name: Build game
      run: cargo check --bin game
    - name: Run tests
      run: cargo test
